### ISSUE TITLE
WHIP client MAY perform trickle ICE or an ICE restarts by sending a HTTP PATCH

### ISSUE THREAD

**Issue by birme** [Eyevinn/whip#9]
Add support for WHIP client and WHIP endpoint to handle trickle ICE or ICE restarts

https://www.ietf.org/archive/id/draft-ietf-wish-whip-01.html#section-4.1

**Comment by marcusspangenberg** [comment]
Implemented trickle-ice support, but leaving out ice restart for now since it's an uncommon case. We can open a new issue for that if needed.
